ansible-community/images

- execution-environments/2.12-with-ansible5/execution-environment.yml
- execution-environments/README.md
The latest image is expected to be more stable than the devel one.
> test-ee:2.12-with-ansible5, use stable-2.12-latest for runner

- ansible-test/README.md
This format is likely more appropriate for listing an increasing amount
of images with various versions of python.
> Reformat available ansible-test images into a table

- ansible-test/centos-stream8/dependencies.txt
These tools were still available in the previous version of the image. Either procps was a (transitive) dependency of something that is installed and no longer is, or it was dropped from the base image.
> Install procps in CentOS Stream 8 to make sure ps and pkill are around

- .github/workflows/ansible-test.yml
- .github/workflows/execution-environments.yml
Prevents that a broken image build kills other potentially working image builds.
> Disable fail-fast in CI

- roles/build-ansible-test-images/tasks/test-image.yml
Subset of #31. If this makes CI pass again that would be great. Otherwise #31 is the next-best solution IMO.
> Explicitly set --docker-network in ansible-test run

- ansible-test/archlinux/build.sh
- ansible-test/centos-stream8/build.sh
- ansible-test/debian-bullseye/build.sh
Improvements of the ansible-test images from https://github.com/ansible-community/images/pull/26 that apply generally.
- 4c8b16bdd40db82a04ecd300e092246fdafd9b69 echos the build commands, so one can more easily figure out where exactly the build breaks (if it does).
- aa3cd9971bd1a57c24659c6661ef1b8d2357a549 sets the timezone for the Arch Linux image to UTC. This avoids systemd asking for the timezone on stdin when starting the container with `--tty`.
> Improve ansible-test images

- ansible-test/README.md
- ansible-test/archlinux/build.sh
- ansible-test/centos-stream8/build.sh
- ansible-test/debian-bullseye/build.sh
This removes the `VOLUME`s from the images.
> Require ansible-core 2.14.0+ for test images

- .github/workflows/ansible-test.yml
- ansible-test/README.md
- ansible-test/centos-stream8/build.sh
- ansible-test/centos-stream8/dependencies.txt
Python 3.6 is the default system Python interpreter for CentOS Stream 8.
This is the interpreter that ansible-core discovers by default. Using
other Python interpreters to execute Ansible modules is unsupported.
Modules that don't use respawning[1] will not able to use Python
bindings for system libraries.
[1] https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/common/respawn.py
---
See https://github.com/ansible-collections/community.general/pull/5638 for more context.
> centos-stream8: Add py3.6 and deprecate py3.8

- .github/workflows/ansible-test.yml
Currently tests fail (https://github.com/ansible-community/images/actions/runs/3651092948) since they are running on Ubuntu 22.04 now.
> Make sure we have the latest ansible-test fixes installed

- .github/workflows/ansible-test.yml
- ansible-test/README.md
- roles/build-ansible-test-images/defaults/main.yml
The tests currently do not want to run with podman or Docker on Zuul. Let's disable the builds for now so at least everything else can proceed.
> Temporarily disable CentOS Stream 8 builds

- ansible-test/archlinux/requirements.txt
- ansible-test/centos-stream8/build.sh
- ansible-test/centos-stream8/requirements-old.txt
- ansible-test/centos-stream8/requirements.txt
- ansible-test/debian-bullseye/requirements.txt
This is also used in the latest distro test images: https://github.com/ansible/distro-test-containers/blob/main/fedora37-test-container/requirements.txt
> Bump coverage to 6.5.0

- .github/workflows/ansible-test.yml
- ansible-test/README.md
- ansible-test/centos-stream8/build.sh
- ansible-test/centos-stream8/dependencies.txt
- roles/build-ansible-test-images/defaults/main.yml
> Remove Python 3.8 support from CentOS Stream 8

- ansible-test/archlinux/build.sh
This impacts CI in community.general and potentially also other collections. Since rewriting all tests to use venvs is pretty expensive, and also ansible-test itself won't do that when using tests/integration/requirements.txt, let's better disable this.
> Arch Linux: remove PEP 668 marker 'EXTERNALLY-MANAGED' for system Python

- .github/workflows/ansible-test.yml
They unfortunately fail for some time now, see https://github.com/ansible-community/images/actions/runs/8493232711/job/23267086510.
> CI: disable running tests with podman

- .github/workflows/ansible-test.yml
- playbooks/publish-ansible-test-images.yml
- roles/build-ansible-test-images/defaults/main.yml
It seems to be broken, as no packages can be installed anymore.
(If re-enabled, we'd need #77.)
> Disable CentOS Stream 8 build

- .github/workflows/eerelease.yml
Automates Community Execution Environment release process. This applies to both community-ee-minimal and community-ee-base.
> Adds code to build and upload Community Execution Environment  via Github Action

- .github/workflows/ansible-test.yml
- ansible-test/centos-stream8/build.sh
- playbooks/publish-ansible-test-images.yml
- roles/build-ansible-test-images/defaults/main.yml
Instead of straight away deleting it, let's build a last version that still allows to run `dnf install` etc.
> Build CentOS Stream 8 image with modified yum baseurl

- .github/workflows/ansible-test.yml
ubuntu-latest (22.04) has an ancient podman which can no longer talk to the Docker version used by GHA...
> CI: try to use a later Ubuntu image

- execution-environments/community-ee-base/execution-environment.yml
- execution-environments/community-ee-minimal/execution-environment.yml
ansible-core version = 2.17.6
fedora  version = 40
ansible.windows = 2.5.0
ansible.posix=  1.6.2
ansible.utils = 4.1.0
> Release: 2.17.6-1 edits core,fedora(40) and collections' versions

- .github/workflows/ansible-test.yml
- .github/workflows/eerelease.yml
- .github/workflows/execution-environments.yml
Fix some issues in GHA workflows pointed out by zizmor (https://github.com/woodruffw/zizmor).
> CI: Fix some issues pointed out by zizmor; improve some more workflows

- ansible-test/archlinux/build.sh
- ansible-test/archlinux/dependencies.txt
Pacman is configured to not extract most locale information. Let's make it stop doing that.
Ref: https://github.com/ansible-collections/community.general/pull/9735
> Arch Linux: make sure locale information provided by glibc is fully installed

- execution-environments/community-ee-base/execution-environment.yml
- execution-environments/community-ee-base/tests.yml
- execution-environments/community-ee-minimal/execution-environment.yml
- execution-environments/community-ee-minimal/tests.yml
This PR:
1. Adds `less` to the community-ee-minimal and community-ee-base images to resolve the issue of `ansible-navigator config list` not working with `--mode stdout` (with new test).
2. Update tests to appease `ansible-lint`.
3. Fixed broken Ansible version tests in community-ee-minimal and community-ee-base (exposed by adding `set -o pipefail` to appease `ansible-lint`) and enhance the `asserts`.
<details><summary><i>community-ee-base</i></summary>
</details>
<details><summary><i>community-ee-minimal</i></summary>
</details>
---
<details><summary><i>community-ee-minimal</i></summary>
```bash
ansible-navigator config list --pp missing --eei ghcr.io/ansible-community/community-ee-minimal:latest --mode stdout
```
</details>
<details><summary><i>community-ee-base</i></summary>
```bash …
```
> Add less to community-ee-[minimal,base] + test updates
