ansible-community/images

ansible-test/centos-stream8/build.sh

Having cowsay active makes it an annoying container for CI :)

Remove cowsay from CentOS 8 Stream container

---

roles/build-ansible-test-images/tasks/main.yml
roles/build-ansible-test-images/tasks/test-image.yml

Paths test

---

playbooks/build-ansible-test-images.yml

podman may need the iptables modules at some point.

load the ip_tables kernel module

---

ansible-test/archlinux/build.sh
ansible-test/debian-bullseye/build.sh

Until we find a better source...

quay.io/official-images/ seems to be dead, let's get the images from Docker Hub

---

playbooks/publish-ansible-test-images.yml

Also disable publishing for CentOS Stream 8

---

.github/workflows/ansible-test.yml
ansible-test/README.md
playbooks/publish-ansible-test-images.yml
roles/build-ansible-test-images/defaults/main.yml

Fixes #49.
Won't work for now...

Re-enable CentOS Stream 8 builds

---

.github/workflows/ansible-test.yml

Ref: https://github.com/ansible-community/images/issues/9#issuecomment-1193351413

Run GHA tests with Podman and Docker

---

.github/workflows/ansible-test.yml
.github/workflows/execution-environments.yml

ansible-core devel no longer likes Python 3.9.

Upgrade Python in CI to 3.11

---

.github/workflows/execution-environments.yml
execution-environments/2.12-with-ansible5/tests.yml
execution-environments/2.15-minimal-with-ansible8/execution-environment.yml
execution-environments/2.15-minimal-with-ansible8/tests.yml
execution-environments/2.15-with-ansible8/execution-environment.yml
execution-environments/2.15-with-ansible8/tests.yml

Updates the Github Action for the new execution environement file

Adds 2.15 ee image and build update

---

execution-environments/community-ee-base/execution-environment.yml
execution-environments/community-ee-minimal/execution-environment.yml

The releases are the following  
-  2.15.5-1 community-ee-base and community-ee-minimal
- 2.15.6-1 community-ee-base and community-ee-minimal
- 2.16.0-1  community-ee-base and community-ee-minimal

Adds the last 3 releases for both ee and minimal

---

ansible-test/README.md

Apparently I have to create a PR :roll_eyes:

Small change to trigger image publish

---

.github/workflows/eerelease.yml

It is helping to debug the workflow on the failure of the job run .

Adds password value in the `Upload image` step

---

docs/community-ee/community-ee-release-process.md

Adding the automated release process via Github action.

Document the automated release process

---

.github/workflows/eerelease.yml

This patch corrects the inputs used in the action for uploading container images to GitHub Container Registry.

Fix uploading EEs to GHCR

---

.gitignore
execution-environments/community-ee-base/execution-environment.yml
execution-environments/community-ee-minimal/execution-environment.yml

make sure python & pip are installed

---

execution-environments/community-ee-base/execution-environment.yml
execution-environments/community-ee-minimal/execution-environment.yml

ansible-core version = 2.18
fedora version = 41
ansible.windows = 2.5.0
ansible.posix= 1.6.2
ansible.utils = 5.1.2

Release: 2.18-1 edits core,fedora(41) and collections' versions

---

execution-environments/community-ee-base/execution-environment.yml
execution-environments/community-ee-minimal/execution-environment.yml

ansible-core version = 2.17.7
fedora version = 41
ansible.windows = 2.5.0
ansible.posix= 1.6.2
ansible.utils = 4.1.0

Release: 2.17.7-1 edits core,fedora(41) and collections' versions

---

docs/community-ee/community-ee-announcement.md

community-ee-announcement.md: add a link to Getting started with EE page

community-ee-announcement.md: add a link to Getting started with EE page

---

ansible-test/archlinux/build.sh

Needed for tests of https://github.com/ansible-collections/community.general/pull/9383 to work.

Arch Linux: make sure to setup machine ID

---

execution-environments/community-ee-base/execution-environment.yml
execution-environments/community-ee-minimal/execution-environment.yml

Updates ansible-core & collection versions for Base and Minimal

---

execution-environments/community-ee-base/execution-environment.yml
execution-environments/community-ee-minimal/execution-environment.yml

This PR updates the ansible-core version to 2.18.7.
The collection version is unchanged .

Updates the ansible-core version for 2.18.7-1
